# Read the documentation at https://github.com/thephpleague/flysystem-bundle/blob/master/docs/1-getting-started.md
flysystem:
    storages:
        default.storage:
            adapter: 'local'
            options:
                directory: '%kernel.project_dir%/storage/%env(SITE)%/'
                permissions:
                    file:
                        public: 0755
                        private: 0700
                    dir:
                        public: 0755
                        private: 0700
