# test environment

version: '3'

services:
   database:
      image: 'postgres:9.6'
      networks:
        default:
           aliases: ['test-db']
      ports:
         - 0.0.0.0:5444:5432
      volumes:
      - ./var/.test-db:/var/lib/postgresql/data
      environment:
         POSTGRES_PASSWORD: 'password'
         POSTGRES_USER: 'user'
         POSTGRES_DB: 'elexp'

networks:
  default:
